type: object
properties:
  feat_0:
    type: number
  feat_1:
    type: number
  feat_2:
    type: number
  feat_3:
    type: number
  feat_4:
    type: number
required:
- feat_0
- feat_1
- feat_2
- feat_3
- feat_4